import {
  Application,
  ApplicationStatus,
  TransactionType,
  Person,
  Role,
  EmploymentRecord,
  PayCadence,
  FinancialEntry,
  FinancialEntryType,
  AssetCategory,
  LiabilityCategory,
  IncomeCategory,
  ExpenseCategory,
} from "@/lib/types";
import { mockBuildings } from "./buildings";

const samplePerson: Person = {
  id: "person-1",
  fullName: "Sarah Johnson",
  email: "sarah.johnson@email.com",
  phone: "(555) 123-4567",
  dob: new Date("1990-05-15"),
  ssnLast4: "1234",
  ssnFull: "123-45-1234",
  role: Role.APPLICANT,
  addressHistory: [
    {
      id: "addr-1",
      street: "100 West End Avenue",
      unit: "12B",
      city: "New York",
      state: "NY",
      zip: "10023",
      fromDate: new Date("2020-01-01"),
      isCurrent: true,
    },
    {
      id: "addr-2",
      street: "456 Amsterdam Avenue",
      unit: "3A",
      city: "New York",
      state: "NY",
      zip: "10024",
      fromDate: new Date("2018-06-01"),
      toDate: new Date("2019-12-31"),
      isCurrent: false,
    },
  ],
};

const sampleEmployment: EmploymentRecord = {
  id: "emp-1",
  employer: "Tech Corporation Inc.",
  title: "Senior Software Engineer",
  startDate: new Date("2019-03-01"),
  payCadence: PayCadence.ANNUAL,
  annualIncome: 150000,
  isCurrent: true,
};

const sampleFinancials: FinancialEntry[] = [
  {
    id: "fin-1",
    entryType: FinancialEntryType.ASSET,
    category: AssetCategory.CHECKING,
    institution: "Chase Bank",
    amount: 50000,
  },
  {
    id: "fin-2",
    entryType: FinancialEntryType.ASSET,
    category: AssetCategory.SAVINGS,
    institution: "Ally Bank",
    amount: 75000,
  },
  {
    id: "fin-3",
    entryType: FinancialEntryType.LIABILITY,
    category: LiabilityCategory.STUDENT_LOAN,
    institution: "Federal Student Aid",
    amount: 25000,
  },
  {
    id: "fin-4",
    entryType: FinancialEntryType.MONTHLY_INCOME,
    category: IncomeCategory.EMPLOYMENT,
    description: "Salary",
    amount: 12500,
  },
  {
    id: "fin-5",
    entryType: FinancialEntryType.MONTHLY_EXPENSE,
    category: ExpenseCategory.RENT_MORTGAGE,
    description: "Current rent",
    amount: 3500,
  },
];

export const mockApplications: Application[] = [
  {
    id: "app-1",
    buildingId: "bldg-1",
    building: mockBuildings[0],
    transactionType: TransactionType.CONDO_PURCHASE,
    status: ApplicationStatus.IN_PROGRESS,
    createdBy: "user-1",
    createdAt: new Date("2025-01-05"),
    lastActivityAt: new Date("2025-01-10"),
    people: [samplePerson],
    employmentRecords: [sampleEmployment],
    financialEntries: sampleFinancials,
    documents: [],
    disclosures: [],
    sections: [
      { key: "profile", label: "Profile", isComplete: true },
      { key: "income", label: "Employment & Income", isComplete: true },
      { key: "financials", label: "Financial Summary", isComplete: true },
      { key: "documents", label: "Documents", isComplete: false },
      { key: "review", label: "Review & Submit", isComplete: false },
    ],
    completionPercentage: 60,
    rfis: [],
    isLocked: false,
  },
  {
    id: "app-2",
    buildingId: "bldg-2",
    building: mockBuildings[1],
    transactionType: TransactionType.COOP_PURCHASE,
    status: ApplicationStatus.SUBMITTED,
    createdBy: "user-3",
    createdAt: new Date("2025-01-01"),
    submittedAt: new Date("2025-01-08"),
    lastActivityAt: new Date("2025-01-08"),
    people: [],
    employmentRecords: [],
    financialEntries: [],
    documents: [],
    disclosures: [],
    sections: [
      { key: "profile", label: "Profile", isComplete: true },
      { key: "income", label: "Employment & Income", isComplete: true },
      { key: "financials", label: "Financial Summary", isComplete: true },
      { key: "documents", label: "Documents", isComplete: true },
      { key: "review", label: "Review & Submit", isComplete: true },
    ],
    completionPercentage: 100,
    rfis: [],
    isLocked: true,
  },
  {
    id: "app-3",
    buildingId: "bldg-3",
    building: mockBuildings[2],
    transactionType: TransactionType.CONDO_LEASE,
    status: ApplicationStatus.IN_REVIEW,
    createdBy: "user-1",
    createdAt: new Date("2024-12-20"),
    submittedAt: new Date("2025-01-02"),
    lastActivityAt: new Date("2025-01-09"),
    people: [],
    employmentRecords: [],
    financialEntries: [],
    documents: [],
    disclosures: [],
    sections: [
      { key: "profile", label: "Profile", isComplete: true },
      { key: "income", label: "Employment & Income", isComplete: true },
      { key: "financials", label: "Financial Summary", isComplete: true },
      { key: "documents", label: "Documents", isComplete: true },
      { key: "disclosures", label: "Disclosures", isComplete: true },
      { key: "review", label: "Review & Submit", isComplete: true },
    ],
    completionPercentage: 100,
    rfis: [],
    isLocked: true,
  },
];
